language: c
os:
        - linux
        - osx

dist: trusty

compiler:  
        - gcc
        - clang

before_install:
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
        - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install flex bison cmake; fi
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qq; fi
        - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qq flex bison cmake; fi

before_script:
        - mkdir build

script: 
        - cd build && cmake .. && make
