language: c

compiler:  
        - gcc
        - clang

matrix:
  include:
        - os: linux
          dist: trusty
          sudo: required
        - os: osx
          osx_image: xcode7.2

before_install:
        - sudo apt-get -qq update
        - sudo apt-get install -y bison
        - sudo apt-get install -y flex

before_script:
        - mkdir build
          
script: 
        - cd build && cmake .. && make && make check
