language: c

compiler:  
        - gcc
        - clang

before_install:
        - sudo apt-get install -qq flex bison
before_script:
        - mkdir build
        - cd build
        - cmake ..
          
script: make
