language: c

compiler:  
        - gcc
        - clang

matrix:
        include:
                - os: linux
                  bison: 3
                - os: osx
                  bison: 3

before_script:
        - mkdir build
          
script: 
        - cd build && cmake .. && make && make check
