language: c

compiler:  
        - gcc
        - clang

before_install:
        - sudo apt-get update -qq
        - sudo apt-get install -qq flex bison cmake

before_script:
        - mkdir build

script: 
        - cd build && cmake .. && make && make check
