language: c

compiler:  
        - gcc
        - clang

before_install:
        - sudo apt-get update -qq

install:
        - sudo apt-get install -qq cmake flex bison

before_script:
        - mkdir build
          
script: 
        - cd build && cmake .. && make && make check
