language: c

compiler:  
        - gcc
        - clang

before_install:
        - sudo apt-get update -y
        - sudo apt-get upgrade -y
        - sudo apt-get install -y flex bison cmake

before_script:
        - mkdir build

script: 
        - cd build && cmake .. && make && make check
