language: c

compiler:  
        - gcc
        - clang

matrix:
        include:
                - os: linux
                  dist: trusty
                  sudo: required
                - os: osx
                  osx_image: xcode7.2

addons:
        apt:
                packages:
                        - bison
                        - flex

before_script:
        - mkdir build
          
script: 
        - cd build && cmake .. && make && make check
